# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 009ff9b3298e39267578d7c493529d2430c8be7e0e4ae7df564246eba2b823f112ec3b40ec498f96eb74b5429cddcec568081ad8c3cefb2083aa550f070c04cf

test:
  secret_key_base: cc724b3be22562c23d9471de7bf24f1465581448d86dac6a16addd360f1542d371c46a4b1e06e9151fc1c143a1994b70fa76eddf6c1c4e4a9bfcd343008ef3f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
